### ISSUE TITLE
Allow Users to Integrate Custom Algorithms into the pipeline

### ISSUE THREAD

**Issue by soutobias** [paidiver/paidiverpy#63]
**Description:**
Users have requested a feature that enables them to integrate their own algorithms into the image processing pipeline defined by a YAML configuration file.

**Proposed Approach:**
1. **Define a Custom Algorithm Interface:**
   Create a base class that all user-defined algorithms must implement. This ensures consistency in execution and parameter handling.

   ```python
   class BaseAlgorithm:
       def __init__(self, params):
           self.params = params
       
       def process(self, image_data):
           raise NotImplementedError("The process method must be implemented by subclasses.")
   ```

2. **Modify the YAML Configuration:**
   Extend the YAML configuration to allow users to specify custom algorithms. Introduce a new section under `steps` where users can define the algorithm's class name and parameters:

   ```yaml
   steps:
     - custom_algorithm:
         name: 'my_custom_algorithm'
         module: 'my_custom_module'  # Path to the user's module
         params:
           some_param: 10
           another_param: 0.5
   ```

3. **Dynamic Algorithm Loading:**
   Implement a mechanism to load user-defined algorithms dynamically using Python’s `importlib`. For example:

   ```python
   import importlib

   def load_custom_algorithm(module_name, class_name, params):
       module = importlib.import_module(module_name)
       algorithm_class = getattr(module, class_name)
       return algorithm_class(params)
   ```

4. **Integrate the Custom Algorithm into the Pipeline:**
   Modify the pipeline execution logic to check for custom algorithms specified in the YAML configuration. If found, load and execute them:

5. **Provide Documentation and Examples:**
   Include clear documentation and examples to guide users on how to create their own algorithms, structure their modules, and configure the YAML file.
